general:
  iflowName: flow1
  iflowVersion: 1.0.1

steps:
  cpiDeployIntegrationDesigntimeArtifact:
    cpiCredentialsId: 87a6418b-2ac1-4839-b22a-b537f55f2176
    integrationFlowId: flow1
    integrationFlowVersion: 1.0.1
    platform: cf
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
  cpiGetiFlowMplStatus:
    cpiCredentialsId: 87a6418b-2ac1-4839-b22a-b537f55f2176
    integrationFlowId: flow1
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
  cpiDownloadiFlowArtifact:
    cpiCredentialsId: 87a6418b-2ac1-4839-b22a-b537f55f2176
    integrationFlowId: flow1
    integrationFlowVersion: 1.0.1
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
  cpiGetiFlowServiceEndpoint:
    cpiCredentialsId: 87a6418b-2ac1-4839-b22a-b537f55f2176
    integrationFlowId: CPI_IFlow_Call_using_Cert
    platform: cf
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
  cpiUpdateIflowDesigntimeConfigurationParameter:
    cpiCredentialsId: 87a6418b-2ac1-4839-b22a-b537f55f2176
    integrationFlowId: httpdynamicUrls
    integrationFlowVersion: 2.1
    platform: cf
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
    parameterKey: myheader
    ParameterValue: test